
version: '2.4'
services:
  proxy:
    container_name: "proxy-server"
    image: "broadinstitute/openidc-proxy:2.3.1_2"
    network_mode: host
    volumes:
    - /home/terra/work/jupyter-server.crt:/etc/ssl/certs/server.crt:ro
    - /home/terra/work/jupyter-server.key:/etc/ssl/private/server.key:ro
    - /home/terra/work/rootCA.pem:/etc/ssl/certs/ca-bundle.crt:ro
    - /home/terra/work/cluster-site.conf:/etc/apache2/sites-enabled/site.conf
    restart: always
    environment:
      HTTPD_PORT: '80'
      SSL_HTTPD_PORT: '443'
      PROXY_SERVER_HOST_NAME: "proxy"
